import sys, unittest
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'tools'))
from c643d.buildscreen import menu_title_lines

class MenuTitleTests(unittest.TestCase):
    def test_release_and_public_renderer(self):
        # Decode the generated bytes to exercise the same include used by ASM.
        for version in ('0.7.1','0.7.2'):
            rows=menu_title_lines(version,'hors-render-v1')
            values=[]
            for row in rows:
                if '.byte' in row:
                    for item in row.split('.byte',1)[1].split(','):
                        item=item.strip();values.append(int(item[1:],16) if item.startswith('$') else int(item))
            titles=bytes(values).split(b'\x00')
            self.assertEqual(titles,[f'C64 3D TOOLKIT {version} HORS-V1'.encode(),b''])
