#!/usr/bin/env python3
"""Run real VICE and compare completed V2/V3/V4 bitmaps/colours with the host oracle.

Uses console mode and a scripted monitor; no X server needed. The matching
.lbl and build/<stem>-stream-vN/oracle.json are generated by cart-stream.
Snapshots are temporary. Pillow is optional, only needed with --capture.
"""
from pathlib import Path
import argparse,json,re,subprocess,sys,tempfile
sys.path.insert(0,str(Path(__file__).resolve().parent))
from c643d.pipeline import decode_record_points
from c643d.colors import C64_PALETTE

def labels(path):
    return {s[2].lstrip('.'):int(s[1],16) for line in path.read_text().splitlines() if len(s:=line.split())==3 and s[0]=='al'}
def expected_frame(f,screen):
    bitmap=bytearray(7680);colors=bytearray([screen])*960
    for rec in f['records']:
        for x,y in decode_record_points(rec):bitmap[(y//8)*320+(x//8)*8+(y&7)] |= 128>>(x&7)
    for lo,hi,n,value in f['color_spans']:
        off=lo+(hi<<8);colors[off:off+n]=bytes([value])*n
    return bitmap,colors

def render_ram(ram,slot):
    from PIL import Image
    im=Image.new('RGB',(320,200));pix=im.load();pal={v[0]:v[1] for v in C64_PALETTE.values()}
    bm=[0x2000,0x6000,0xe000][slot];sc=[0x400,0x4400,0xc800][slot]
    for y in range(200):
        for x in range(320):
            cell=(y//8)*40+x//8;color=ram[sc+cell];bit=ram[bm+cell*8+(y&7)]&(128>>(x&7))
            pix[x,y]=pal[color>>4 if bit else color&15]
    return im

def verify(crt,vice,vice_data=None,cycles=2,capture=None,menu_entry=None):
    root=Path(__file__).resolve().parents[1];crt=Path(crt).resolve()
    if menu_entry is None:
        sym=labels(crt.with_suffix('.lbl'))
        manifest=json.loads(crt.with_name(crt.stem+'-manifest.json').read_text());screen=manifest['screen_color'];menu=None
        variant=manifest['renderer'].rsplit('-',1)[1];work=root/'build'/f'{crt.stem}-stream-{variant}'
    else:
        manifest=json.loads(crt.with_name(crt.stem+'-cart-manifest.json').read_text())
        if manifest.get('uniform_renderer'):
            if not 0<=menu_entry<len(manifest['streamed_entries']):raise ValueError('menu entry out of range')
            entry=manifest['streamed_entries'][menu_entry]
            work=root/entry['work'];screen=entry['screen_color']
            manifest['colors']=entry['colors']
        else:
            if menu_entry not in (10,11):raise ValueError('mixed menu stream entries are 10=horse and 11=sunflower')
            name=('horse_head_hifi','sunflower_torus_hifi')[menu_entry-10]
            screen=manifest['streamed_entries'][menu_entry-10]['screen_color']
            variant=manifest.get('stream_renderer','yunroll-cart-v2').rsplit('-',1)[1]
            work=root/f'build/menu-stream-{variant}'/name
        sym=labels(work/'runtime.lbl')
        menu=labels(root/'build'/f'{crt.stem}-cartridge-demo'/f'{crt.stem}-runtime-default.lbl')
    frames=json.loads((work/'oracle.json').read_text());n=len(frames);count=n*cycles+3
    # publish_wait can revisit the publication entry on very cheap frames.
    # Stop at the once-per-frame call site, before the handoff wait instead.
    completed=sym.get('frame_draw_complete',sym['frame_begin']+(15 if manifest.get('colors',True) else 12))
    with tempfile.TemporaryDirectory(prefix='c643d-vice-') as td:
        td=Path(td);mon=['delete']
        if menu is not None:
            mon += [f'break ${menu["menu_wait_key"]:04x}','g','delete',f'> ${menu["selected_entry"]:04x} ${menu_entry:02x}',f'break ${completed:04x}']
            first_go=f'g ${menu["menu_launch_nowait"]:04x}'
        else:
            mon += [f'break ${completed:04x}'];first_go='g'
        for i in range(count):mon += [first_go if i==0 else 'g','bank ram',f'bsave "{td/f"frame-{i:04d}.ram"}" 0 $0000 $ffff','stopwatch']
        mon += ['quit'];(td/'run.mon').write_text('\n'.join(mon)+'\n')
        cmd=[vice,'-console','+sound','-warp','-seed','1','-cartcrt',str(crt),'-initbreak','reset','-moncommands',str(td/'run.mon'),'-monlog','-monlogname',str(td/'monitor.log'),'-limitcycles',str(count*1000000+2000000)]
        if vice_data:cmd+=['-directory',str(vice_data)]
        with (td/'vice.log').open('w') as log:subprocess.run(cmd,stdout=log,stderr=subprocess.STDOUT,timeout=180,check=True)
        ticks=[int(x) for x in re.findall(r'Stopwatch:\s*(\d+)',(td/'monitor.log').read_text())]
        if len(ticks)!=count:raise AssertionError('Emulator did not reach every completed frame: '+(td/'monitor.log').read_text()[-1800:])
        slot_counts={};images=[]
        for i in range(count):
            ram=(td/f'frame-{i:04d}.ram').read_bytes();fi=ram[sym['frame_index']];slot=ram[sym['render_slot']]
            assert fi==i%n,(i,fi)
            slot_counts[slot]=slot_counts.get(slot,0)+1
            bm,sc=expected_frame(frames[fi],screen)
            baddr=[0x2000,0x6000,0xe000][slot];saddr=[0x400,0x4400,0xc800][slot]
            for what,want,actual in [('bitmap',bm,ram[baddr:baddr+7680]),('colour',sc,ram[saddr:saddr+960])]:
                if want!=actual:
                    mismatch=[j for j,(a,b) in enumerate(zip(want,actual)) if a!=b]
                    raise AssertionError(f'{crt.stem} frame {i} slot {slot}: {what} mismatch ({len(mismatch)} bytes), first {mismatch[:12]}')
            if capture and n<=i<2*n:images.append(render_ram(ram,slot))
        assert set(slot_counts)=={0,1,2},slot_counts
        delta=[b-a for a,b in zip(ticks,ticks[1:])];clock=985248
        result=dict(cartridge=crt.name,menu_entry=menu_entry,verified_frames=count,orientations=n,bitmap_bytes_checked=count*7680,color_bytes_checked=count*960,slots=slot_counts,average_fps=clock*(count-1)/(ticks[-1]-ticks[0]),min_frame_cycles=min(delta),max_frame_cycles=max(delta),pixel_match=True,color_match=True)
        if capture and images:
            capture=Path(capture);capture.mkdir(parents=True,exist_ok=True)
            from PIL import Image
            images[0].resize((960,600),Image.Resampling.NEAREST).save(capture/f'{crt.stem}-vice.png')
            durations=[max(10,round(delta[n+i]/clock*1000)) for i in range(n)]
            images[0].resize((640,400),Image.Resampling.NEAREST).save(capture/f'{crt.stem}-vice.gif',save_all=True,append_images=[im.resize((640,400),Image.Resampling.NEAREST) for im in images[1:]],duration=durations,loop=0)
        return result
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('crt',type=Path);p.add_argument('--vice',default='x64sc');p.add_argument('--vice-data');p.add_argument('--cycles',type=int,default=2);p.add_argument('--capture',type=Path);p.add_argument('--report',type=Path);p.add_argument('--menu-entry',type=int);a=p.parse_args()
    if a.cycles<2 and a.capture:p.error('--capture requires at least two cycles')
    r=verify(a.crt,a.vice,a.vice_data,a.cycles,a.capture,a.menu_entry);text=json.dumps(r,indent=2);print(text)
    if a.report:a.report.write_text(text+'\n')
